
name: Sync Back to Dev Branch 84

on:
  push:
    branches:
      - '84_shift_overleaf'

jobs:
  sync_back:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from mirror
      uses: actions/checkout@v2
      with:
        ref: '84_shift_overleaf'

    - name: Checkout dev repository
      run: |
        git clone https://github.com/ShiqiYang2022/template_84
        git fetch --unshallow
        cd template_84
        git checkout master 

    - name: Merge and Push
      run: |
        cd template_84
        git pull ../ 84_shift_overleaf
        git config pull.rebase false
        git push origin master
