
name: Sync Back to Dev Branch 84

on:
  push:
    branches:
      - 'master'

jobs:
  sync_back:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from mirror
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Checkout dev repository
      run: |
        git clone https://github.com/ShiqiYang2022/template_84
        cd template_84
        git checkout 84_shift_overleaf

    - name: Merge and Push
      run: |
        cd template_84
        git pull ../
        git push origin 84_shift_overleaf
